# 应用端口
server:
  port: 80

spring:
  # 设置数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///graduate?setTimezone=UTC
      username: root
      password: root

# 配置 Mybatis Plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto